#!/usr/bin/env bash
# Configures Nginx to include custom X-Served-By header

apt-get update -y
apt-get install nginx -y

# Add X-Served-By header with the server's hostname
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default

service nginx restart