#!/usr/bin/env bash
# Installs and configures HAproxy load balancer

apt-get update -y
apt-get install haproxy -y

# Enable HAproxy init script
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAproxy
sudo cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log local0
    maxconn 2048
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server divin-web-01 54.197.77.181:80 check
    server divin-web-02 52.91.48.189:80 check
EOF

service haproxy restart