#!/usr/bin/env bash
# Installs nginx server

apt-get update -y
apt-get install -y nginx

# Ensure nginx is started and enabled
systemctl start nginx
systemctl enable nginx

# Configure default page
echo "Holberton School" > /var/www/html/index.html

# Restart to apply changes
systemctl restart nginx