#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

apt-get update -y
apt-get install -y nginx

mkdir -p /var/www/html

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure nginx with custom 404 page
cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

service nginx start
service nginx reload